export default{
onboarding1:require('../assets/images/ic_1.png'),
backarrow:require('../assets/images/ic_back_arrow.png'),
mainlogo:require('../assets/images/ic_main_logo.png'),
googlelogo: require('../assets/images/ic_google.png'),
facebooklogo: require('../assets/images/ic_facebook.png'),
applelogo: require('../assets/images/ic_apple.png'),
check:require('../assets/images/ic_grey_tick.png'),
homelogo:require('../assets/images/ic_home_icon.png'),
locationicon:require('../assets/images/ic_loc.png'),
dots:require('../assets/images/ic_dots.png'),
sharearrow:require('../assets/images/ic_direction.png'),
banner:require('../assets/images/banner.jpeg'),
cross:require('../assets/images/ic_cross.png'),
icHome:require('../assets/images/ic_home.png'),
icSearch:require('../assets/images/ic_srch.png'),
icUser:require('../assets/images/ic_user.png'),
icNotify:require('../assets/images/ic_notify.png'),
icAdd:require('../assets/images/ic_add.png'),
icUser1:require('../assets/images/ic_usrr_1.png'),
icChangepwd:require('../assets/images/ic_key.png'),
icSignout:require('../assets/images/ic_logout.png'),
icPlus:require('../assets/images/ic_plus.png'),
icHomeActive:require('../assets/images/ic_red_home.png'),
icAddActive:require('../assets/images/ic_red_add.png'),
icBlueTick:require('../assets/images/ic_blue_tick.png')
}