export default{
    Hendrerit_vulputate_sem:'Hendrerit vulputate sem',
    Aenean_et_aenean:'Aenean et convallis nulla. Donec in efficitur nisi, et vestibulum quam aenean.',
    Get_Started:'GET STARTED',
    Welcome:'Welcome Back!',
    We_are_Happy:'We are happy to see. You can login to continue.',
    Create_a_new_account:'Create a new account',
    Create_an_account_so_you_can_continue:"Create an account so you can continue.",
    UseOTP:'UseOTP',
    Forgot_password:'Forgot password?',
    Login:'LOGIN',
    Mobile_No:'Mobile number',
    Password:'Password',
    Email:'Email',
    Signup:'SIGNUP',
    First_Name:'First Name',
    Last_Name:'Last Name',
    New_here:'New here? ',
    Sign_Up:'Sign Up',
    LogIn_Google:'Log In with Google',
    LogIn_Facebook:'Log In with Facebook',
    LogIn_Apple:'Log In with Apple',
    LogIn_Phone_No:'Log In with Phone number',
    By_clicking_privacy_policy:'By clicking “Log In”, you agree with our Terms. Learn how we process your data in our Privacy policy.',
    Set_password:'Set password',
    Create_secure_and_unique_password:'Create secure and unique password.',
    Confirm_password:'Confirm password',
    Enter_4_Digit:'Enter the 4-digit code sent to you at',
    Edit_My_Number:'Edit my mobile number',
    Resend_Otp_in:'Resend code in '
}